#!/bin/sh
# Created to do i3 like movements within groups

last_commands=""

handle() {
  case $1 in
    activewindow*)
        # Fetching data from hyprctl
        monitors=$(hyprctl -j monitors)
        clients=$(hyprctl -j clients)

        # Searching for the active monitor
        active_monitor=$(echo "$monitors" | jq '.[] | select(.focused==true)')

        # Checking if there is a specialWorkspace
        if [ -n "$(echo "$active_monitor" | jq -r '.specialWorkspace.name')" ]; then
            active_workspace=$(echo "$active_monitor" | jq -r '.specialWorkspace.name')
        else
            active_workspace=$(echo "$active_monitor" | jq -r '.activeWorkspace.name')
        fi

        # Checking if windows in the active workspace have 'grouped'
        windows_in_active_workspace=$(echo "$clients" | jq -c ".[] | select(.workspace.name==\"$active_workspace\")")
        grouped_windows_in_active_workspace=$(echo "$windows_in_active_workspace" | jq -c 'select(.grouped | length > 0)')

        # Checking if windows in the group are the only ones in the active workspace
        if [ "$(echo "$grouped_windows_in_active_workspace" | jq -s '. | length')" -gt 0 ] && [ "$(echo "$windows_in_active_workspace" | jq -s '. | length')" == "$(echo "$grouped_windows_in_active_workspace" | jq -s '. | length')" ]; then
            new_commands="group"
            if [ "$last_commands" != "$new_commands" ]; then
                hyprctl keyword unbind SUPER,J
                hyprctl keyword unbind SUPER,K
                hyprctl keyword unbind SUPER SHIFT,J
                hyprctl keyword unbind SUPER SHIFT,K
                hyprctl keyword bind SUPER,J, changegroupactive, f
                hyprctl keyword bind SUPER,K, changegroupactive, b
                hyprctl keyword bind SUPER SHIFT,J, movegroupwindow, f
                hyprctl keyword bind SUPER SHIFT,K, movegroupwindow, b
                last_commands=$new_commands
            fi
        else
            new_commands="layout"
            if [ "$last_commands" != "$new_commands" ]; then
                hyprctl keyword unbind SUPER,J
                hyprctl keyword unbind SUPER,K
                hyprctl keyword unbind SUPER SHIFT,J
                hyprctl keyword unbind SUPER SHIFT,K
                hyprctl keyword bind SUPER,J,layoutmsg,cyclenext
                hyprctl keyword bind SUPER,K,layoutmsg,cycleprev
                hyprctl keyword bind SUPER SHIFT,J,layoutmsg,swapnext
                hyprctl keyword bind SUPER SHIFT,K,layoutmsg,swapprev
                last_commands=$new_commands
            fi
        fi
    ;;
  esac
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done