#!/bin/sh
# Created to do i3 like movements within groups

last_commands=""

handle() {
  case $1 in
    activewindow*)
        # Fetching data from hyprctl
        monitors=$(hyprctl -j monitors)
        clients=$(hyprctl -j clients)

        # Searching for the active monitor
        active_monitor=$(echo "$monitors" | jq '.[] | select(.focused==true)')

        # Checking if there is a specialWorkspace
        if [ -n "$(echo "$active_monitor" | jq -r '.specialWorkspace.name')" ]; then
            active_workspace=$(echo "$active_monitor" | jq -r '.specialWorkspace.name')
        else
            active_workspace=$(echo "$active_monitor" | jq -r '.activeWorkspace.name')
        fi

        # Checking if windows in the active workspace have 'grouped'
        windows_in_active_workspace=$(echo "$clients" | jq -c ".[] | select(.workspace.name==\"$active_workspace\")")
        grouped_windows_in_active_workspace=$(echo "$windows_in_active_workspace" | jq -c 'select(.grouped | length > 0)')

        # Checking if windows in the group are the only ones in the active workspace
        if [ "$(echo "$grouped_windows_in_active_workspace" | jq -s '. | length')" -gt 0 ] && [ "$(echo "$windows_in_active_workspace" | jq -s '. | length')" == "$(echo "$grouped_windows_in_active_workspace" | jq -s '. | length')" ]; then
            new_commands="group"
            if [ "$last_commands" != "$new_commands" ]; then
                hyprctl eval 'hl.unbind("SUPER + J")'
                hyprctl eval 'hl.unbind("SUPER + K")'
                hyprctl eval 'hl.unbind("SUPER + SHIFT + J")'
                hyprctl eval 'hl.unbind("SUPER + SHIFT + K")'
                hyprctl eval 'hl.bind("SUPER + J", hl.dsp.group.next())'
                hyprctl eval 'hl.bind("SUPER + K", hl.dsp.group.prev())'
                hyprctl eval 'hl.bind("SUPER + SHIFT + J", hl.dsp.group.move_window({ forward = true }))'
                hyprctl eval 'hl.bind("SUPER + SHIFT + K", hl.dsp.group.move_window({ forward = false }))'
                last_commands=$new_commands
            fi
        else
            new_commands="layout"
            if [ "$last_commands" != "$new_commands" ]; then
                hyprctl eval 'hl.unbind("SUPER + J")'
                hyprctl eval 'hl.unbind("SUPER + K")'
                hyprctl eval 'hl.unbind("SUPER + SHIFT + J")'
                hyprctl eval 'hl.unbind("SUPER + SHIFT + K")'
                hyprctl eval 'hl.bind("SUPER + J", hl.dsp.layout("cyclenext"))'
                hyprctl eval 'hl.bind("SUPER + K", hl.dsp.layout("cycleprev"))'
                hyprctl eval 'hl.bind("SUPER + SHIFT + J", hl.dsp.layout("swapnext"))'
                hyprctl eval 'hl.bind("SUPER + SHIFT + K", hl.dsp.layout("swapprev"))'
                last_commands=$new_commands
            fi
        fi
    ;;
  esac
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
